// Generated by `bun init`

/** Public env vars embedded by Bun (`bun build --env='BUN_PUBLIC_*'`, dev server loads `.env`). */
interface ImportMetaEnv {
  readonly BUN_PUBLIC_GITHUB_ENDPOINT?: string;
  readonly BUN_PUBLIC_GITHUB_PAT?: string;
  readonly BUN_PUBLIC_OMDB_ENDPOINT?: string;
  readonly BUN_PUBLIC_OMDB_API_KEY?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
