// Generated by `bun init`

/** Use literal `process.env.BUN_PUBLIC_*` in client code so Bun can inline from `.env` (see `bunfig.toml` `[serve.static].env`). */
declare namespace NodeJS {
  interface ProcessEnv {
    BUN_PUBLIC_GITHUB_ENDPOINT?: string;
    BUN_PUBLIC_GITHUB_PAT?: string;
    BUN_PUBLIC_OMDB_ENDPOINT?: string;
    BUN_PUBLIC_OMDB_API_KEY?: string;
    /** Optional; defaults to https://randomuser.me/api/ in code. */
    BUN_PUBLIC_RANDOM_USER_API?: string;
  }
}

interface ImportMetaEnv {
  readonly BUN_PUBLIC_GITHUB_ENDPOINT?: string;
  readonly BUN_PUBLIC_GITHUB_PAT?: string;
  readonly BUN_PUBLIC_OMDB_ENDPOINT?: string;
  readonly BUN_PUBLIC_OMDB_API_KEY?: string;
  readonly BUN_PUBLIC_RANDOM_USER_API?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
